name: ZAP

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The full URL of the site to scan (e.g. https://example.com)'
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Full Scan

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ github.event.inputs.target_url }}
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: '-a'
          allow_issue_writing: true
          artifact_name: 'zap_scan_results'
